name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_generative_ai: ^0.4.7
  speech_to_text: ^7.3.0
  geolocator: ^13.0.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
